export const actionTypes = {
    ALERT: {
        SUCCESS: 'ALERT_SUCCESS',
        ERROR: 'ALERT_ERROR',
        CLEAR: 'ALERT_CLEAR',
    },
    AUTH: {
        LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
        LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
        LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
        LOGOUT: 'USERS_LOGOUT',
    },
    USERS: {
        GETALL_REQUEST: 'USERS_GETALL_REQUEST',
        GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
        GETALL_FAILURE: 'USERS_GETALL_FAILURE',
    },
    SCHEDULES: {
        GETALL_REQUEST: 'SCHEDULES_GETALL_REQUEST',
        GETALL_SUCCESS: 'SCHEDULES_GETALL_SUCCESS',
        GETALL_FAILURE: 'SCHEDULES_GETALL_FAILURE',

        ADD_REQUEST: 'SCHEDULES_ADD_REQUEST',
        ADD_SUCCESS: 'SCHEDULES_ADD_SUCCESS',
        ADD_FAILURE: 'SCHEDULES_ADD_FAILURE',

        DELETE_REQUEST: 'SCHEDULES_DELETE_REQUEST',
        DELETE_SUCCESS: 'SCHEDULES_DELETE_SUCCESS',
        DELETE_FAILURE: 'SCHEDULES_DELETE_FAILURE',

        UPDATE_ORDER_BY: 'SCHEDULES_UPDATE_ORDER_BY',
        UPDATE_ORDER_DIR: 'SCHEDULES_UPDATE_ORDER_DIR',
        UPDATE_QUERY_TEXT: 'SCHEDULES_UPDATE_QUERY_TEXT'
    }
};